name: Node CI

on: [push, pull_request]

jobs:
  build-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: add yarn
        uses: Borales/actions-yarn@v2.1.0
#       - name: Use Node.js 12.x
#         uses: actions/setup-node@v1.4.2
#         with:
#           node-version: '12'
      - name: build
        run: |
          yarn build
      - name: since api tests cant be tested on github CI, we need to find a way to seperate them
        run: echo TODO
        env:
          CI: true
